version: 0.2

phases:
  build:
    commands:
      - zip -r function.zip .

      - aws lambda update-function-code \
        --function-name LeaveManagementFunction \
        --zip-file fileb://function.zip
